CREATE SEQUENCE SQ_LOGS START 1;

CREATE TABLE public.LOG_AUDITORIA (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	servico varchar(255) NOT NULL,
    data timestamp NOT NULL,
    operacao int NOT NULL,
    url varchar(500),
    conteudo varchar(2000),
    pai int8,
	CONSTRAINT log_aud_pkey PRIMARY KEY (id),
    CONSTRAINT log_aud_pai_fkey FOREIGN KEY (pai)
        REFERENCES public.LOG_AUDITORIA(id)
);